const data = {
  products: [
    {
      id: "1",
      name: "Nike Slim shirts",
      category: "Shirts",
      image: "/images/product2.jpg",
      price: "1200",
      brand: "Nike",
      rating: "4.5",
      numReviews: "10",
      description: "High quality",
    },
    {
      id: "2",
      name: "Glasses",
      category: "Eyeglass",
      image: "/images/product3.jpg",
      price: "22000",
      brand: "opera",
      rating: "4.5",
      numReviews: "10",
      description: "low quality",
    },
    {
      id: "3",
      name: "Addidas Bags",
      category: "Bags",
      image: "/images/product4.jpg",
      price: "4200",
      brand: "Addidas",
      rating: "3.5",
      numReviews: "20",
      description: "High quality",
    },
    {
      id: "4",
      name: "Nike Shoes",
      category: "Shoes",
      image: "/images/product3.jpg",
      price: "1200",
      brand: "Nike",
      rating: "4.5",
      numReviews: "10",
      description: "High quality",
    },
    {
      id: "5",
      name: "Jackets",
      category: "Jackets",
      image: "/images/product5.jpg",
      price: "1200",
      brand: "Nike",
      rating: "4.5",
      numReviews: "10",
      description: "High quality",
    },
    {
      id: "6",
      name: "Bags",
      category: "Shirts",
      image: "/images/product6.jpg",
      price: "1200",
      brand: "Nike",
      rating: "4.5",
      numReviews: "10",
      description: "High quality",
    },
  ],
};
export default data;
