const data = {
  products: [
    {
      name: "Nike Slim shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/product1.jpg",
      price: "1200",
      CountInStock: 14,
      brand: "Nike",
      rating: "4.5",
      numReviews: "20",
      description: "High quality",
    },
    {
      name: "Hand-Bag",
      slug: "hand-bag",
      category: "Mens clothes",
      image: "/images/product2.jpg",
      price: "22000",
      CountInStock: 24,
      brand: "opera",
      rating: "4.8",
      numReviews: "10",
      description: "low quality",
    },
    {
      name: "Jackets",
      slug: "jackets",
      category: "pullovers",
      image: "/images/product3.jpg",
      price: "4200",
      CountInStock: 34,
      brand: "Addidas",
      rating: "4.5",
      numReviews: "20",
      description: "High quality",
    },
    {
      name: "Nike Shoes",
      slug: "nike-shoes",
      category: "Shoes",
      image: "/images/product4.jpg",
      price: "1200",
      CountInStock: 24,
      brand: "Nike",
      rating: "4.5",
      numReviews: "15",
      description: "High quality",
    },
    {
      name: "Rain Jackets",
      slug: "rain-jackets",
      category: "rain-jackets",
      image: "/images/product5.jpg",
      price: "1200",
      CountInStock: 24,
      brand: "Nike",
      rating: "4.5",
      numReviews: "10",
      description: "High quality",
    },
    {
      name: "Eye glasses",
      slug: "eye-glasses",
      category: "Shirts",
      image: "/images/product6.jpg",
      price: "1200",
      CountInStock: 44,
      brand: "Nike",
      rating: "3.5",
      numReviews: "17",
      description: "High quality",
    },
  ],
};
export default data;
